apiVersion: v1
kind: Service
metadata:
  name: svc-login
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30200
    protocol: TCP
  selector:
    app: webui